/**
 * 电台数据配置 - 百品专用
 */
var radioStations = [
    // === 香港 ===
    { name: "香港电台第一台 (RTHK1)", url: "https://rthkaudio1-lh.akamaihd.net/i/radio1_1@355864/master.m3u8", logo: "https://radio.baipon.com/img/radio/rthk.ico", category: "香港" },
    { name: "香港电台第二台 (RTHK2)", url: "https://rthkaudio2-lh.akamaihd.net/i/radio2_1@355865/master.m3u8", logo: "https://radio.baipon.com/img/radio/rthk.ico", category: "香港" },
    { name: "香港电台第三台 (RTHK3 English)", url: "https://rthkaudio3-lh.akamaihd.net/i/radio3_1@355866/master.m3u8", logo: "https://radio.baipon.com/img/radio/rthk.ico", category: "香港" },
    { name: "香港电台第四台 (Classical)", url: "https://rthkaudio4-lh.akamaihd.net/i/radio4_1@355867/master.m3u8", logo: "https://radio.baipon.com/img/radio/rthk.ico", category: "香港" },
    { name: "香港电台第五台 (RTHK5)", url: "https://rthkaudio5-lh.akamaihd.net/i/radio5_1@355868/master.m3u8", logo: "https://radio.baipon.com/img/radio/rthk.ico", category: "香港" },
    { name: "香港电台第六台转播香港之声", url: "https://rthkradiocnrhk-live.akamaized.net/hls/live/2046111/radiocnrhk/master.m3u8", logo: "https://radio.baipon.com/img/radio/rthk.ico", category: "香港" },
    { name: "香港电台普通话台 (RTHK Mandarin)", url: "https://rthkaudio6-lh.akamaihd.net/i/radiopth_1@355869/master.m3u8", logo: "https://radio.baipon.com/img/radio/rthk.ico", category: "香港" },
    { name: "香港电台转播大湾区之声", url: "https://rthkradiocmgrgb-live.akamaized.net/hls/live/2046112/radiocmgrgb/index_64_a.m3u8", logo: "https://radio.baipon.com/img/radio/rthk.ico", category: "香港" },

    { name: "新城知讯台 (997)", url: "https://1603884249.rsc.cdn77.org/1603884249/index.m3u8", logo: "https://www.metroradio.com.hk/SuperHome/2022/images/img_logo_metro-app2023.svg", category: "香港" },
    { name: "新城财经台 (104)", url: "https://1716664847.rsc.cdn77.org/1716664847/index.m3u8", logo: "https://www.metroradio.com.hk/SuperHome/2022/images/img_logo_metro-app2023.svg", category: "香港" },
    { name: "新城采讯台 (Metro Plus AM1044)", url: "http://162.220.162.10:8011/stream?n=16c3fc38112458291459", logo: "https://www.metroradio.com.hk/SuperHome/2022/images/img_logo_metro-app2023.svg", category: "香港" },
    
    { name: "雷霆881 商业一台", url: "https://d2agljdoug3z0j.cloudfront.net/radio-HTTP/cr1-hd.3gp/chunklist.m3u8", logo: "https://www.881903.com/favicon.ico", category: "香港" },
    { name: "叱咤903 商业二台", url: "https://d2agljdoug3z0j.cloudfront.net/radio-HTTP/cr2-hd.3gp/chunklist.m3u8", logo: "https://www.881903.com/favicon.ico", category: "香港" },
    { name: "豁达864", url: "https://d3ca3xccq5z5hu.cloudfront.net/radio-HTTP/am864.3gp/chunklist.m3u8", logo: "https://www.881903.com/favicon.ico", category: "香港" },

    { name: "Radio Lantau", url: "https://radio.dripfeed.net/listen/radiolantau/radio.mp3", logo: "https://radiolantau.com/templates/radiowave/favicon.ico", category: "香港" },
    { name: "遠東廣播 良友電台", url: "https://a.listenz.net/ly729_a", logo: "https://729ly.net/images/ly_favicon.png", category: "香港"},

    // === 澳门 ===
    { name: "澳门电台 (中文) Macau Radio (Chinese)", url: "https://globallive.tdm.com.mo/live/rch2.live/playlist.m3u8", logo: "https://cdn2.tdm.com.mo/uploads/media/web_images/tdm new app logo.png", category: "澳门" },
    { name: "澳门电台 (葡文) Macau Radio (Portuguese)", url: "https://globallive.tdm.com.mo/live/rch1.live/playlist.m3u8", logo: "https://cdn2.tdm.com.mo/uploads/media/web_images/tdm new app logo.png", category: "澳门" },
    { name: "绿邨电台 Radio Vilaverde", url: "https://fm995.ddns.net/hls1/fm995.m3u8", logo: "https://mfm995.com/wp-content/uploads/2022/09/cropped-icon20220930_1.png", category: "澳门" },

    // === 内地 (CNR / CMG / CRI) ===
    { name: "中国之声 (Voice of China)", url: "https://radioback.baipon.com/api/live?name=中国之声&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "经济之声 (Voice of Biz)", url: "https://radioback.baipon.com/api/live?name=经济之声&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "音乐之声 (Voice of Music)", url: "https://radioback.baipon.com/api/live?name=音乐之声&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "经典音乐广播 (Golden Radio)", url: "https://radioback.baipon.com/api/live?name=经典音乐广播&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "台海之声 Cross-Strait Radio", url: "https://radioback.baipon.com/api/live?name=台海之声&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "神州之声 Easy Radio", url: "https://radioback.baipon.com/api/live?name=神州之声&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "大湾区之声 Voice of the Great Bay", url: "https://radioback.baipon.com/api/live?name=大湾区之声&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "香港之声 Voice of Hong Kong", url: "https://radioback.baipon.com/api/live?name=香港之声&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "民族之声 Minority Language Radio", url: "https://radioback.baipon.com/api/live?name=民族之声&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "文艺之声 Voice of Art", url: "https://radioback.baipon.com/api/live?name=文艺之声&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "老年之声 Voice of Old", url: "https://radioback.baipon.com/api/live?name=老年之声&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "中国乡村之声 China Countryside Radio", url: "https://radioback.baipon.com/api/live?name=中国乡村之声&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "南海之声 Voice of South China Sea", url: "https://radioback.baipon.com/api/live?name=南海之声&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "藏语广播 Tibetan Radio", url: "https://radioback.baipon.com/api/live?name=藏语广播&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "维吾尔语广播 Uyghur Radio", url: "https://radioback.baipon.com/api/live?name=维吾尔语广播&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "哈萨克语广播 Kazakh Radio", url: "https://radioback.baipon.com/api/live?name=哈萨克语广播&type=hls", logo: "https://radio.baipon.com/img/radio/cnr.ico", category: "内地" },
    { name: "中国交通广播（北京）China Traffic Radio (Beijing)", url: "https://radioback.baipon.com/api/live?name=中国交通广播&type=hls", logo: "https://radio.baipon.com/img/radio/CNTR.ico", category: "内地" },
    { name: "中国交通广播（雄安） China Traffic Radio (Xiong'an)", url: "https://radioback.baipon.com/api/local?name=中国交通广播（雄安）&type=mp3", logo: "https://radio.baipon.com/img/radio/CNTR.ico", category: "内地" },
    { name: "中国交通广播（安徽） China Traffic Radio (Anhui)", url: "https://radioback.baipon.com/api/local?name=中国交通广播（安徽）&type=mp3", logo: "https://radio.baipon.com/img/radio/CNTR.ico", category: "内地" },
    { name: "中国交通广播（湖南） China Traffic Radio (Hunan)", url: "https://radioback.baipon.com/api/local?name=中国交通广播（湖南）&type=mp3", logo: "https://radio.baipon.com/img/radio/CNTR.ico", category: "内地" },
    { name: "中国交通广播（四川） China Traffic Radio (Sichuan)", url: "https://radioback.baipon.com/api/local?name=中国交通广播（四川）&type=mp3", logo: "https://radio.baipon.com/img/radio/CNTR.ico", category: "内地" },
    { name: "中国交通广播（江西） China Traffic Radio (Jiangxi)", url: "https://radioback.baipon.com/api/local?name=中国交通广播（江西）&type=mp3", logo: "https://radio.baipon.com/img/radio/CNTR.ico", category: "内地" },
    { name: "中国交通广播（河北） China Traffic Radio (Hebei)", url: "https://radioback.baipon.com/api/local?name=中国交通广播（河北）&type=mp3", logo: "https://radio.baipon.com/img/radio/CNTR.ico", category: "内地" },
    { name: "中国交通广播（长三角） China Traffic Radio (Yangtze River Delta)", url: "https://radioback.baipon.com/api/local?name=中国交通广播（长三角）&type=mp3", logo: "https://radio.baipon.com/img/radio/CNTR.ico", category: "内地" },


    { name: "华语环球广播 Global Chinese Radio", url: "http://sk.cri.cn/hyhq.m3u8", logo: "https://www.cri.cn/favicon.ico", category: "内地" },
    { name: "环球资讯广播 Global News Radio", url: "http://sk.cri.cn/905.m3u8", logo: "https://www.cri.cn/favicon.ico", category: "内地" },
    { name: "英语资讯广播 (CGTN Radio)", url: "https://sk.cri.cn/am846.m3u8", logo: "https://www.cri.cn/favicon.ico", category: "内地" },
    { name: "世界华声 Chinese Dialect Radio", url: "http://sk.cri.cn/hxfh.m3u8", logo: "https://www.cri.cn/favicon.ico", category: "内地" },

    // === 台湾 ===
    // 警察广播电台（含补充分台）
    { name: "警察广播电台 全国治安交通网", url: "https://stream.pbs.gov.tw/live/PBS/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/pbs.ico", category: "台湾" },
    { name: "警察广播电台 台北分台", url: "https://stream.pbs.gov.tw/live/TPS/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/pbs.ico", category: "台湾" },
    { name: "警察广播电台 台中分台", url: "https://stream.pbs.gov.tw/live/TCS/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/pbs.ico", category: "台湾" },
    { name: "警察广播电台 台南分台", url: "https://stream.pbs.gov.tw/live/TNS/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/pbs.ico", category: "台湾" },
    { name: "警察广播电台 高雄分台", url: "https://stream.pbs.gov.tw/live/KSS/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/pbs.ico", category: "台湾" },
    { name: "警察广播电台 宜兰分台", url: "https://stream.pbs.gov.tw/live/ELS/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/pbs.ico", category: "台湾" },
    { name: "警察广播电台 花莲分台", url: "https://stream.pbs.gov.tw/live/HLS/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/pbs.ico", category: "台湾" },
    { name: "警察广播电台 台东分台", url: "http://stream.pbs.gov.tw:1935/live/TTS/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/pbs.ico", category: "台湾" },
    { name: "警察广播电台 新竹分台", url: "http://stream.pbs.gov.tw:1935/live/SCS/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/pbs.ico", category: "台湾" },

    // 中央广播电台 (RTI)
    { name: "中央广播电台 国语台 (RTI)", url: "https://streamak0138.akamaized.net/live0138lh-mbm9/_definst_/rti3/playlist.m3u8", logo: "https://www.rti.org.tw/favicon.ico", category: "台湾" },
    { name: "中央廣播電臺 台客粵語和歐美外語 (RTI)", url: "https://streamak0138.akamaized.net/live0138lh-mbm9/_definst_/rti6/playlist.m3u8", logo: "https://www.rti.org.tw/favicon.ico", category: "台湾" },
    { name: "講客廣播電臺 (RTI Hakka)", url: "https://stream.rcs.revma.com/akqrbx94gbkvv", logo: "https://www.hakkaradio.org.tw/logos/hakkaradio_256.png", category: "台湾" },

    // 其他台湾电台（含补充）
    { name: "ICRT 台北国际社区广播电台", url: "https://stream.rcs.revma.com/nkdfurztxp3vv", logo: "https://www.icrt.com.tw/favicon.ico", category: "台湾" },
    { name: "CityFM 台中城市广播 (929)", url: "http://fm929.cityfm.tw:8080/929.mp3", logo: "https://radio.baipon.com/img/radio/cityfm.ico", category: "台湾" },
    { name: "CityFM 台北健康电台 (901)", url: "http://fm901.cityfm.tw:8080/901.mp3", logo: "https://radio.baipon.com/img/radio/cityfm.ico", category: "台湾" },
    { name: "CityFM 大苗栗 (983)", url: "http://fm983.cityfm.tw:8080/983.mp3", logo: "https://radio.baipon.com/img/radio/cityfm.ico", category: "台湾" },
    { name: "CityFM 台南知音 (971)", url: "http://fm971.cityfm.tw:8080/971.mp3", logo: "https://radio.baipon.com/img/radio/cityfm.ico", category: "台湾" },
    { name: "M-Radio 全国", url: "http://stream.rcs.revma.com/044q61ha7a0uv", logo: "https://www.mradio.com.tw/favicon.ico", category: "台湾" },

    { name: "Classical FM 97.7", url: "https://onair.family977.com.tw:8977/live.mp3", logo: "https://radio.baipon.com/img/radio/classical.ico", category: "台湾" },
    { name: "BravoFM 91.3台北都会音乐台", url: "https://onair.bravo913.com.tw:9130/live.mp3", logo: "https://www.bravo913.com.tw/lazyweb/images/logo.png", category: "台湾" },
    { name: "News 98", url: "https://stream.rcs.revma.com/pntx1639ntzuv.m4a", logo: "http://www.news98.com.tw/images/neil.ico", category: "台湾" },
    { name: "IC之音 竹科廣播電台", url: "https://stream.rcs.revma.com/7mnq8rt7k5zuv", logo: "https://www.ic975.com/favicon.svg", category: "台湾" },
    { name: "臺北廣播電臺93.1", url: "https://stream.ginnet.cloud/live0130lo-yfyo/_definst_/fm/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/tr.ico", category: "台湾" },
    { name: "中廣流行網", url: "https://sonnykuo.appspot.com/bcc/?id=中廣流行網", logo: "https://radio.baipon.com/img/radio/bcc.ico", category: "台湾" },
    { name: "中廣音樂網", url: "https://sonnykuo.appspot.com/bcc/?id=中廣音樂網", logo: "https://radio.baipon.com/img/radio/bcc.ico", category: "台湾" },
    { name: "中廣新聞網", url: "https://sonnykuo.appspot.com/bcc/?id=中廣新聞網", logo: "https://radio.baipon.com/img/radio/bcc.ico", category: "台湾" },
    { name: "中廣鄉親網", url: "https://sonnykuo.appspot.com/bcc/?id=中廣鄉親網", logo: "https://radio.baipon.com/img/radio/bcc.ico", category: "台湾" },
    { name: "中廣I go 531", url: "https://stream.rcs.revma.com/1qxn2vg3qtzuv", logo: "https://radio.baipon.com/img/radio/bcc.ico", category: "台湾" },
    { name: "飛碟聯播網", url: "https://stream.rcs.revma.com/em90w4aeewzuv.m4a", logo: "https://www.uforadio.com.tw/frontend_assets/img/logo-s.png", category: "台湾" },
    { name: "AsiaFM 亞洲電台", url: "https://stream.rcs.revma.com/xpgtqc74hv8uv", logo: "https://www.asiafm.com.tw/wp-content/uploads/2023/03/logo-footer-04.png", category: "台湾" },
    { name: "AsiaFM 亚太电台 FM92.3", url: "https://stream.rcs.revma.com/kydend74hv8uv", logo: "https://www.asiafm.com.tw/wp-content/themes/asiafm/images/logo.png", category: "台湾" },
    { name: "AsiaFM 飞扬调频 FM89.5", url: "https://stream.rcs.revma.com/e0tdah74hv8uv", logo: "https://www.asiafm.com.tw/wp-content/themes/asiafm/images/logo.png", category: "台湾" },
    { name: "Hit FM 台北之音", url: "http://202.39.43.67:1935/live/RA000036/chunklist.m3u8", logo: "https://www.hitoradio.com/newweb/imgs/logo_2013.jpg", category: "台湾" },
    { name: "好事聯播網", url: "http://202.39.43.67:1935/live/RA000013/chunklist.m3u8", logo: "http://www.bestradio.com.tw/images/logo.png", category: "台湾" },
    { name: "台北流行廣播POP Radio", url: "http://202.39.43.67:1935/live/RA000080/chunklist.m3u8", logo: "https://www.pop917.com/images/logo_2025.png", category: "台湾" },
    { name: "台北愛樂电台", url: "http://202.39.43.67:1935/live/RA000018/chunklist.m3u8", logo: "https://www.e-classical.com.tw/img/favicon.ico", category: "台湾" },
    { name: "幸福电台 FM102.5", url: "http://61.218.61.251:8080", logo: "https://www.tr幸福广播.tw/favicon.ico", category: "台湾" },
    { name: "世新广播电台 88.1", url: "https://stream.ginnet.cloud/live0115lo-89xv/_definst_/fm881/playlist.m3u8", logo: "https://shrs.shu.edu.tw/wp-content/uploads/2021/04/logo.png", category: "台湾" },
    { name: "台艺之声 88.3", url: "https://votastream.ntua.edu.tw:8443/vota", logo: "https://vota.ntua.edu.tw/member/vota88_3/upload_file/vota88_3/461/16159474612.png", category: "台湾" },
    { name: "辅大之声 88.5", url: "http://fjuvoice885.fju.edu.tw:8000/fjuvoice885.mp3", logo: "https://www.fjucomm.com/fjuvoice885/wp-content/uploads/2017/07/logo%E7%99%BD%E5%B0%8F-01.png", category: "台湾" },
    { name: "政大之声 88.7", url: "http://vnccuonair.nccu.edu.tw:8000/ade.taiwan.mp3", logo: "https://vnccu.nccu.edu.tw/assets/images/style70/kv-small1.jpg", category: "台湾" },
    { name: "淡江之声 88.7", url: "http://163.13.182.81:8001/votk", logo: "https://radio.baipon.com/img/radio/votk.ico", category: "台湾" },
    { name: "铭传之声 88.3", url: "http://radio.mcu.edu.tw:8080/radio", logo: "http://radio.mcu.edu.tw/wp-content/uploads/2021/12/foot_pic_3-300x300-1.jpg", category: "台湾" },
    { name: "佳音Love联播网", url: "https://stream.ginnet.cloud/live0119lo-p4rb/_definst_/fm909/playlist.m3u8", logo: "http://www.goodnews.org.tw/favicon.ico", category: "台湾" },
    { name: "渔业广播电台", url: "https://stream.rcs.revma.com/mk0c5vq122hvv", logo: "https://radio.baipon.com/img/radio/frs.ico", category: "台湾" },
    { name: "正声综合台", url: "http://flv.ccdntech.com/live/_definst_/mp4:vod117_Live/live2/playlist.m3u8", logo: "https://www.csbc.com.tw/wp-content/uploads/2019/05/02.app%E5%8D%80%E5%A1%8A.png", category: "台湾" },
    { name: "正声 104.1", url: "http://flv.ccdntech.com/live/_definst_/mp4:vod117_Live/live1/playlist.m3u8", logo: "https://www.csbc.com.tw/wp-content/uploads/2019/05/02.app%E5%8D%80%E5%A1%8A.png", category: "台湾" },
    { name: "UNI FM96.7 环宇广播电台", url: "https://n10.rcs.revma.com/srn5f9kmwxhvv", logo: "https://radio.baipon.com/img/radio/uni.ico", category: "台湾" },
    { name: "漢聲廣播電台", url: "http://202.39.43.67:1935/live/RA000076/chunklist.m3u8", logo: "https://radio.baipon.com/img/radio/voh.ico", category: "台湾" },
    { name: "国立教育广播电台/台北 101.7", url: "https://cast.ner.gov.tw/1", logo: "https://www.ner.gov.tw/icon.jpg", category: "台湾" },
    { name: "領袖廣播電台 FM93.7", url: "https://stream.rcs.revma.com/hpeqh9mkc6hvv", logo: "https://fm937fm.com/assets/images/icon-32x33.png", category: "台湾" },
    { name: "GoGoRadio 桃園 FM104.3", url: "https://stream.ginnet.cloud/live0119lo-p4rb/_definst_/fm1043/playlist.m3u8", logo: "https://gogoradiofm1043.com.tw/favicon.ico", category: "台湾" },
    { name: "高雄廣播電臺 FM94.3", url: "https://stream.rcs.revma.com/pet2dvug1bkvv", logo: "https://www.kbs.gov.tw/images/favicon/apple-touch-icon-114x114.png", category: "台湾" },
        
    { name: "LOVE 972", url: "https://14033.live.streamtheworld.com/LOVE972FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/love-972.png", category: "新加坡" },
    { name: "YES 933", url: "https://22393.live.streamtheworld.com/YES933_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/yes-933.png", category: "新加坡" },
    { name: "CNA 938", url: "https://14033.live.streamtheworld.com/938NOW_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/cna-938.png", category: "新加坡" },
    { name: "CAPITAL 958", url: "https://19183.live.streamtheworld.com/CAPITAL958FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/capital-958.png", category: "新加坡" },
    { name: "CLASS 95", url: "https://14033.live.streamtheworld.com/CLASS95_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/class-95.png", category: "新加坡" },
    { name: "GOLD 905", url: "https://14033.live.streamtheworld.com/GOLD905_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/gold-905.png", category: "新加坡" },
    { name: "987FM", url: "https://14033.live.streamtheworld.com/987FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/987.png", category: "新加坡" },
    { name: "SYMPHONY 924", url: "https://14033.live.streamtheworld.com/SYMPHONY924FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/symphony-924.png", category: "新加坡" },
    { name: "RIA 897", url: "https://14033.live.streamtheworld.com/RIA897FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/ria-897.png", category: "新加坡" },
    { name: "Oli 968", url: "https://14033.live.streamtheworld.com/OLI968FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/oli-968.png", category: "新加坡" },
    { name: "Warna 942", url: "https://14033.live.streamtheworld.com/WARNA942FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/warna-942.png", category: "新加坡" },
    { name: "UFM 100.3", url: "https://28093.live.streamtheworld.com/UFM_1003AAC.aac", logo: "https://www.ufm1003.sg/wp-content/assets/5/img/NAV_01_Logo_1003.svg", category: "新加坡" },
    { name: "96.3 好FM", url: "https://22243.live.streamtheworld.com/HAO_963AAC.aac", logo: "https://static.moneyfm893.sg/uploads/sites/7/2024/08/HaoFm-fullcolor-copy.svg", category: "新加坡" },
    { name: "One FM 91.3", url: "https://22283.live.streamtheworld.com/ONE_FM_913AAC.aac", logo: "https://www.onefm.sg/wp-content/assets/3/img/NAV_01_Logo_913-new.svg", category: "新加坡" },
    { name: "Kiss92 FM", url: "https://22283.live.streamtheworld.com/KISS_92AAC.aac", logo: "https://www.kiss92.sg/wp-content/assets/4/img/NAV_01_Logo_920.svg", category: "新加坡" },
    { name: "Power 98 Love Songs", url: "https://28093.live.streamtheworld.com/POWER98_LOVESONGS_SC", logo: "https://radio.baipon.com/img/radio/power98.ico", category: "新加坡" },

    // === 国际 / 其他 ===
    { name: "BBC World Service", url: "https://stream.live.vc.bbcmedia.co.uk/bbc_world_service", logo: "https://www.bbc.com/favicon.ico", category: "国际" },
    { name: "半岛电视台 (Al Jazeera English)", url: "https://live-hls-audio-web-aje.getaj.net/VOICE-AJE/01.m3u8", logo: "https://www.aljazeera.com/favicon.ico", category: "国际" },
    { name: "Linn Jazz", url: "http://89.16.185.174:8004/stream", logo: "https://small.linncdn.com/website/responsive/images/favicon.ico", category: "国际" },
    { name: "NHK 世界广播 (中文)", url: "https://nhkworld.webcdn.stream.ne.jp/www11/radiojapan/all/263948/live_s.m3u8", logo: "https://www.nhk.or.jp/favicon.ico", category: "国际" },
    { name: "VOA Global English", url: "http://voa-ingest.akamaized.net/hls/live/2035200/161_352R/playlist.m3u8", logo: "https://www.voachinese.com/Content/responsive/VOA/zh-CN/img/logo.svg", category: "国际" },

    // === 网络音乐 ===
    { name: "V2BEAT", url: "https://stream.v2beat.live/icecast.audio?t=file.mp3", logo: "", category: "网络音乐" },
    { name: "AsiaFM 亚洲音乐", url: "http://asiafm.hk:8000/asiafm", logo: "", category: "网络音乐" },
    { name: "AsiaFM HD音乐", url: "http://asiafm.hk:8000/asiahd", logo: "", category: "网络音乐" },
    { name: "AsiaFM 亚洲经典", url: "http://goldfm.cn:8000/goldfm", logo: "", category: "网络音乐" },
    { name: "AsiaFM 亚洲热歌", url: "http://hot.asiafm.net:8000/asiafm", logo: "", category: "网络音乐" },
    { name: "AsiaFM 亚洲天空", url: "http://funradio.cn:8000/funradio", logo: "", category: "网络音乐" },
    { name: "AsiaFM 亚洲粤语", url: "http://yyt.asiafm.net:8000/asiafm", logo: "", category: "网络音乐" },
    { name: "80后音悦台", url: "http://stream3.hndt.com/now/SFZeH2cb/playlist.m3u8", logo: "", category: "网络音乐" },
    { name: "500首华语经典", url: "http://ls.qingting.fm/live/3412131.m3u8?bitrate=64", logo: "", category: "网络音乐" },
    { name: "Big B Chinese 中文流行", url: "https://antares.dribbcast.com/proxy/cpop?mp=/s", logo: "https://bigbradio.net/sites/default/files/favicon.ico", category: "网络音乐" },
    { name: "Big B Korean 韩语流行", url: "https://antares.dribbcast.com/proxy/kpop?mp=/s", logo: "https://bigbradio.net/sites/default/files/favicon.ico", category: "网络音乐" },
    { name: "Big B Japanese 日语流行", url: "https://antares.dribbcast.com/proxy/jpop?mp=/s", logo: "https://bigbradio.net/sites/default/files/favicon.ico", category: "网络音乐" },
    { name: "Big B Radio Aisa 亚洲流行", url: "https://antares.dribbcast.com/proxy/apop?mp=/s", logo: "https://bigbradio.net/sites/default/files/favicon.ico", category: "网络音乐" },
    { name: "Chinese Music World 中国古典音乐", url: "http://radio.chinesemusicworld.com/listen.pls", logo: "https://chinesemusicworld.com/wp-content/uploads/2012/03/logo.png", category: "网络音乐" },

    
    // === 美国 (USA) ===
    { name: "NPR News (美国全国公共广播)", url: "https://npr-ice.streamguys1.com/live.mp3", logo: "https://www.npr.org/favicon.ico", category: "美国" },
    { name: "WNYC New York (纽约公共广播)", url: "https://fm939.wnyc.org/wnycfm-mobile.aac", logo: "https://www.wnyc.org/favicon.ico", category: "美国" },
    { name: "KEXP Seattle (西雅图独立音乐)", url: "https://kexp-mp3-128.streamguys1.com/kexp128.mp3", logo: "https://www.kexp.org/favicon.ico", category: "美国" },
    { name: "WQXR (纽约古典音乐台)", url: "https://wqxr.streaming.adswizz.com/wqxr-mobile.mp3", logo: "https://www.wqxr.org/favicon.ico", category: "美国" },
    { name: "SomaFM Groove Salad (旧金山电子)", url: "http://ice1.somafm.com/groovesalad-128-mp3", logo: "https://somafm.com/favicon.ico", category: "美国" },
    { name: "Bloomberg Radio (彭博财经)", url: "https://playerservices.streamtheworld.com/api/livestream-redirect/WBBRAMAAC.aac", logo: "https://www.bloomberg.com/favicon.ico", category: "美国" },
    { name: "Jazz24 (全天候爵士乐)", url: "https://live.wpmucdn.com/kplu/jazz24-mp3-128", logo: "https://www.jazz24.org/favicon.ico", category: "美国" },
    { name: "CNBC Business News", url: "https://vpr.streamguys1.com/vpr64.mp3", logo: "https://www.cnbc.com/favicon.ico", category: "美国" },
    { name: "CNN International", url: "https://radio13.servidorderadio.net:7034/stream", logo: "https://www.cnn.com/favicon.ico", category: "美国" },
    { name: "ABC News Radio", url: "http://live-radio02.mediahubaustralia.com/PBW/mp3/;", logo: "https://abcnews.go.com/favicon.ico", category: "美国" },
    { name: "Fox News Radio", url: "https://prod-54-86-8-179.amperwave.net/foxnewsradio-foxnewsradioaac-imc?session-id=5ac631347bd8726df027e928c287b215", logo: "https://www.foxnews.com/favicon.ico", category: "美国" },
    { name: "C-SPAN Radio (美国公共事务广播)", url: "https://vpr.streamguys1.com/vpr64.mp3", logo: "https://www.c-span.org/favicon.ico", category: "美国" },
    { name: "Canada Fairchid Radio 加拿大中文電台", url: "https://stream.eseenet.com/radio/am1430.stream/chunklist_w1528612212.m3u8", logo: "https://www.am1430.com/favicon.ico", category: "美国" },
    { name: "US Chinese Radio (Seattle) 美國中文電台（西雅圖）", url: "http://kxparadio.serverroom.us:5852/stream.mp3", logo: "https://static.wixstatic.com/media/8a3185_3c8a42561e2c462a955a0136261cba84~mv2.jpg", category: "美国" },
    { name: "US Chinese Radio (San Francisco) 美國中文電台（舊金山）", url: "http://radiokest.serverroom.us:6670/;?type=http&nocache=3295", logo: "https://static.wixstatic.com/media/8a3185_3c8a42561e2c462a955a0136261cba84~mv2.jpg", category: "美国" },
    { name: "WZRC AM1480 Cantonese 紐約華語廣播（廣東話）", url: "https://video1.getstreamhosting.com:8288/stream", logo: "https://nysino.com/am1480/wp-content/uploads/2021/03/am1480logo.png", category: "美国" },
    { name: "WZRC AM1380 Mandarin 紐約華語廣播（普通話）", url: "https://video1.getstreamhosting.com:8292/stream", logo: "https://www.nysino.com/am1380/wp-content/uploads/2022/06/am1380-logo.png", category: "美国" },
    { name: "1150 AM KKNW （中文廣播時間：UTC-8 9pm-12am（6pm Fri.-Sun.））", url: "https://16643.live.streamtheworld.com/KKNWAMAAC.aac", logo: "https://kknwamsite.wpenginepowered.com/wp-content/uploads/2020/08/cropped-kknw_logo_default.png", category: "美国" },
    { name: "2CR澳洲中文廣播電台", url: "https://streaming.shoutcast.com/2cr-chinese-radio", logo: "https://d1cce5idf8ce8i.cloudfront.net/wp-content/themes/woo/images/favicon.jpg", category: "美国" },


    // === 欧洲 ===
    { name: "Czech Evropa 2", url: "https://29093.live.streamtheworld.com/EVROPA2AAC.aac", logo: "https://radio.baipon.com/img/radio/evropa2.ico", category: "欧洲" },
    { name: "Czech Hitradio City", url: "https://22183.live.streamtheworld.com/HITRADIO_CITY_PRAHA.aac", logo: "https://radio.baipon.com/img/radio/hitradio.ico", category: "欧洲" },
    { name: "Germany Antenne Bayern", url: "https://stream.antenne.de/antenne", logo: "https://www.antenne.de/favicon.ico", category: "欧洲" },
    { name: "Germany WDR 1", url: "https://wdr-1live-live.icecast.wdr.de/wdr/1live/live/mp3/128/stream.mp3", logo: "https://www1.wdr.de/favicon.ico", category: "欧洲" },
    { name: "Switzerland SRF 3", url: "https://stream.srg-ssr.ch/m/srf3/mp3_128", logo: "https://www.srf.ch/favicon.ico", category: "欧洲" },
    { name: "Netherlands Radio 538", url: "https://25533.live.streamtheworld.com/RADIO538.mp3", logo: "https://www.538.nl/favicon.ico", category: "欧洲" },
    { name: "France Inter", url: "https://stream.radiofrance.fr/franceinter/franceinter_midfi.m3u8?id=radiofrance", logo: "https://radio.baipon.com/img/radio/franceinter.ico", category: "欧洲" },
    { name: "France Info", url: "https://stream.radiofrance.fr/franceinfo/franceinfo_lofi.m3u8?id=radiofrance", logo: "https://radio.baipon.com/img/radio/franceinfo.ico", category: "欧洲" },
    { name: "France Culture", url: "https://stream.radiofrance.fr/franceculture/franceculture_hifi.m3u8?id=radiofrance", logo: "https://radio.baipon.com/img/radio/franceculture.ico", category: "欧洲" },
    { name: "France Musique", url: "https://stream.radiofrance.fr/francemusique/francemusique.m3u8?id=radiofrance", logo: "https://radio.baipon.com/img/radio/francemusique.ico", category: "欧洲" },
    { name: "France FIP", url: "https://stream.radiofrance.fr/fip/fip.m3u8?id=radiofrance", logo: "https://radio.baipon.com/img/radio/fip.ico", category: "欧洲" },
    { name: "France Mouv'", url: "https://stream.radiofrance.fr/mouv/mouv_hifi.m3u8?id=radiofrance", logo: "https://radio.baipon.com/img/radio/mouv.ico", category: "欧洲" },
    { name: "France Bleu(ICI) 100% Franch Music", url: "https://stream.radiofrance.fr/fbchansonfrancaise/fbchansonfrancaise_hifi.m3u8?id=radiofrance", logo: "https://radio.baipon.com/img/radio/ici.ico", category: "欧洲" },
    { name: "France Bleu(ICI) 100% années 80", url: "https://stream.radiofrance.fr/fb100pour100annees80/fb100pour100annees80_hifi.m3u8?id=radiofrance", logo: "https://radio.baipon.com/img/radio/ici.ico", category: "欧洲" },
    { name: "Klassik Radio", url: "https://stream.klassikradio.de/national/aac-128/select?aggregator=select&metaid=85f19f80-d068-4f41-8a64-85b37009a39e&rmsid=select-web", logo: "https://klassikradioplus.de/build/images/apple-touch-icon.png", category: "欧洲" },
    { name: "欧洲华语广播电台 Radio Mandarin d'Europe", url: "http://rme.stream.dicast.fr:8000/rme-192.mp3", logo: "https://www.radiomandarin.fr/images/logo.png", category: "欧洲" },
    { name: "BBC - Radio 1", url: "http://as-hls-ww-live.akamaized.net/pool_01505109/live/ww/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio 1Xtra", url: "http://as-hls-ww-live.akamaized.net/pool_92079267/live/ww/bbc_1xtra/bbc_1xtra.isml/bbc_1xtra-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio 1Dance", url: "http://as-hls-ww-live.akamaized.net/pool_62063831/live/ww/bbc_radio_one_dance/bbc_radio_one_dance.isml/bbc_radio_one_dance-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio 1 Anthems (UK Only)", url: "http://as-hls-uk-live.akamaized.net/pool_11351741/live/uk/bbc_radio_one_anthems/bbc_radio_one_anthems.isml/bbc_radio_one_anthems-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio 2", url: "http://as-hls-ww-live.akamaized.net/pool_74208725/live/ww/bbc_radio_two/bbc_radio_two.isml/bbc_radio_two-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio 3", url: "http://as-hls-ww-live.akamaized.net/pool_23461179/live/ww/bbc_radio_three/bbc_radio_three.isml/bbc_radio_three-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio 3 Unwind (UK Only)", url: "http://as-hls-uk-live.akamaized.net/pool_30624046/live/uk/bbc_radio_three_unwind/bbc_radio_three_unwind.isml/bbc_radio_three_unwind-audio%3d320000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio 4", url: "http://as-hls-ww-live.akamaized.net/pool_55057080/live/ww/bbc_radio_fourfm/bbc_radio_fourfm.isml/bbc_radio_fourfm-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio 4 Extra", url: "http://as-hls-ww-live.akamaized.net/pool_26173715/live/ww/bbc_radio_four_extra/bbc_radio_four_extra.isml/bbc_radio_four_extra-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio 5 live", url: "http://as-hls-ww-live.akamaized.net/pool_89021708/live/ww/bbc_radio_five_live/bbc_radio_five_live.isml/bbc_radio_five_live-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio 6 Music", url: "http://as-hls-ww-live.akamaized.net/pool_81827798/live/ww/bbc_6music/bbc_6music.isml/bbc_6music-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio 5 Live sports extra (UK Only)", url: "http://as-hls-uk-live.akamaized.net/pool_47700285/live/uk/bbc_radio_five_live_sports_extra/bbc_radio_five_live_sports_extra.isml/bbc_radio_five_live_sports_extra-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Asian Network", url: "http://as-hls-ww-live.akamaized.net/pool_22108647/live/ww/bbc_asian_network/bbc_asian_network.isml/bbc_asian_network-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - BBC World Service", url: "http://as-hls-ww-live.akamaized.net/pool_87948813/live/ww/bbc_world_service/bbc_world_service.isml/bbc_world_service-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - BBC CWR", url: "http://as-hls-ww-live.akamaized.net/pool_79805333/live/ww/bbc_radio_coventry_warwickshire/bbc_radio_coventry_warwickshire.isml/bbc_radio_coventry_warwickshire-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - BBC Essex", url: "http://as-hls-ww-live.akamaized.net/pool_23657270/live/ww/bbc_radio_essex/bbc_radio_essex.isml/bbc_radio_essex-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - BBC Hereford Worcester", url: "http://as-hls-ww-live.akamaized.net/pool_80112859/live/ww/bbc_radio_hereford_worcester/bbc_radio_hereford_worcester.isml/bbc_radio_hereford_worcester-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Berkshire", url: "http://as-hls-ww-live.akamaized.net/pool_64162474/live/ww/bbc_radio_berkshire/bbc_radio_berkshire.isml/bbc_radio_berkshire-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Bristol", url: "http://as-hls-ww-live.akamaized.net/pool_41858929/live/ww/bbc_radio_bristol/bbc_radio_bristol.isml/bbc_radio_bristol-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Cambridge", url: "http://as-hls-ww-live.akamaized.net/pool_21074581/live/ww/bbc_radio_cambridge/bbc_radio_cambridge.isml/bbc_radio_cambridge-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Cornwall", url: "http://as-hls-ww-live.akamaized.net/pool_72477894/live/ww/bbc_radio_cornwall/bbc_radio_cornwall.isml/bbc_radio_cornwall-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Cumbria", url: "http://as-hls-ww-live.460020/live/ww/bbc_radio_cumbria/bbc_radio_cumbria.isml/bbc_radio_cumbria-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Cymru", url: "http://as-hls-ww-live.akamaized.net/pool_24792333/live/ww/bbc_radio_cymru/bbc_radio_cymru.isml/bbc_radio_cymru-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Cymru 2", url: "http://as-hls-ww-live.akamaized.net/pool_98610936/live/ww/bbc_radio_cymru_2/bbc_radio_cymru_2.isml/bbc_radio_cymru_2-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Derby", url: "http://as-hls-ww-live.akamaized.net/pool_63732303/live/ww/bbc_radio_derby/bbc_radio_derby.isml/bbc_radio_derby-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Devon", url: "http://as-hls-ww-live.akamaized.net/pool_08856933/live/ww/bbc_radio_devon/bbc_radio_devon.isml/bbc_radio_devon-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Foyle", url: "http://as-hls-ww-live.akamaized.net/pool_43178797/live/ww/bbc_radio_foyle/bbc_radio_foyle.isml/bbc_radio_foyle-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Gloucestershire", url: "http://as-hls-ww-live.akamaized.net/pool_74607547/live/ww/bbc_radio_gloucestershire/bbc_radio_gloucestershire.isml/bbc_radio_gloucestershire-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Guernsey", url: "http://as-hls-ww-live.akamaized.net/pool_65313722/live/ww/bbc_radio_guernsey/bbc_radio_guernsey.isml/bbc_radio_guernsey-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Humberside", url: "http://as-hls-ww-live.akamaized.net/pool_43379345/live/ww/bbc_radio_humberside/bbc_radio_humberside.isml/bbc_radio_humberside-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Jersey", url: "http://as-hls-ww-live.akamaized.net/pool_14000630/live/ww/bbc_radio_jersey/bbc_radio_jersey.isml/bbc_radio_jersey-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Kent", url: "http://as-hls-ww-live.akamaized.net/pool_17754185/live/ww/bbc_radio_kent/bbc_radio_kent.isml/bbc_radio_kent-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Lancashire", url: "http://as-hls-ww-live.akamaized.net/pool_98146551/live/ww/bbc_radio_lancashire/bbc_radio_lancashire.isml/bbc_radio_lancashire-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Leeds", url: "http://as-hls-ww-live.akamaized.net/pool_50115440/live/ww/bbc_radio_leeds/bbc_radio_leeds.isml/bbc_radio_leeds-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Leicester", url: "http://as-hls-ww-live.akamaized.net/pool_04542919/live/ww/bbc_radio_leicester/bbc_radio_leicester.isml/bbc_radio_leicester-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Lincolnshire", url: "http://as-hls-ww-live.akamaized.net/pool_77667780/live/ww/bbc_radio_lincolnshire/bbc_radio_lincolnshire.isml/bbc_radio_lincolnshire-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio London", url: "http://as-hls-ww-live.akamaized.net/pool_98137350/live/ww/bbc_london/bbc_london.isml/bbc_london-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Manchester", url: "http://as-hls-ww-live.akamaized.net/pool_25317916/live/ww/bbc_radio_manchester/bbc_radio_manchester.isml/bbc_radio_manchester-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Merseyside", url: "http://as-hls-ww-live.akamaized.net/pool_46699767/live/ww/bbc_radio_merseyside/bbc_radio_merseyside.isml/bbc_radio_merseyside-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio nan Gaidheal", url: "http://as-hls-ww-live.akamaized.net/pool_01935182/live/ww/bbc_radio_nan_gaidheal/bbc_radio_nan_gaidheal.isml/bbc_radio_nan_gaidheal-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Newcastle", url: "http://as-hls-ww-live.akamaized.net/pool_46887953/live/ww/bbc_radio_newcastle/bbc_radio_newcastle.isml/bbc_radio_newcastle-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Norfolk", url: "http://as-hls-ww-live.akamaized.net/pool_61510571/live/ww/bbc_radio_norfolk/bbc_radio_norfolk.isml/bbc_radio_norfolk-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Northampton", url: "http://as-hls-ww-live.akamaized.net/pool_73827654/live/ww/bbc_radio_northampton/bbc_radio_northampton.isml/bbc_radio_northampton-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Nottingham", url: "http://as-hls-ww-live.akamaized.net/pool_96088503/live/ww/bbc_radio_nottingham/bbc_radio_nottingham.isml/bbc_radio_nottingham-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Orkney", url: "http://as-hls-ww-live.akamaized.net/pool_50082558/live/ww/bbc_radio_orkney/bbc_radio_orkney.isml/bbc_radio_orkney-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Oxford", url: "http://as-hls-ww-live.akamaized.net/pool_19212690/live/ww/bbc_radio_oxford/bbc_radio_oxford.isml/bbc_radio_oxford-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Scotland FM", url: "http://as-hls-ww-live.akamaized.net/pool_43322914/live/ww/bbc_radio_scotland_fm/bbc_radio_scotland_fm.isml/bbc_radio_scotland_fm-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Scotland MW", url: "http://as-hls-ww-live.akamaized.net/pool_59378121/live/ww/bbc_radio_scotland_mw/bbc_radio_scotland_mw.isml/bbc_radio_scotland_mw-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Sheffield", url: "http://as-hls-ww-live.akamaized.net/pool_19967704/live/ww/bbc_radio_sheffield/bbc_radio_sheffield.isml/bbc_radio_sheffield-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Shropshire", url: "http://as-hls-ww-live.akamaized.net/pool_83478576/live/ww/bbc_radio_shropshire/bbc_radio_shropshire.isml/bbc_radio_shropshire-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Solent", url: "http://as-hls-ww-live.akamaized.net/pool_11685351/live/ww/bbc_radio_solent/bbc_radio_solent.isml/bbc_radio_solent-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Solent West Dorset", url: "http://as-hls-ww-live.akamaized.net/pool_48517520/live/ww/bbc_radio_solent_west_dorset/bbc_radio_solent_west_dorset.isml/bbc_radio_solent_west_dorset-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Somerset Sound", url: "http://as-hls-ww-live.akamaized.net/pool_00727706/live/ww/bbc_radio_somerset_sound/bbc_radio_somerset_sound.isml/bbc_radio_somerset_sound-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Stoke", url: "http://as-hls-ww-live.akamaized.net/pool_34849862/live/ww/bbc_radio_stoke/bbc_radio_stoke.isml/bbc_radio_stoke-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Suffolk", url: "http://as-hls-ww-live.akamaized.net/pool_18067288/live/ww/bbc_radio_suffolk/bbc_radio_suffolk.isml/bbc_radio_suffolk-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Surrey", url: "http://as-hls-ww-live.akamaized.net/pool_27374427/live/ww/bbc_radio_surrey/bbc_radio_surrey.isml/bbc_radio_surrey-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Sussex", url: "http://as-hls-ww-live.akamaized.net/pool_76643803/live/ww/bbc_radio_sussex/bbc_radio_sussex.isml/bbc_radio_sussex-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Tees", url: "http://as-hls-ww-live.akamaized.net/pool_08918172/live/ww/bbc_tees/bbc_tees.isml/bbc_tees-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Ulster", url: "http://as-hls-ww-live.akamaized.net/pool_31244774/live/ww/bbc_radio_ulster/bbc_radio_ulster.isml/bbc_radio_ulster-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Wales", url: "http://as-hls-ww-live.akamaized.net/pool_97517794/live/ww/bbc_radio_wales_fm/bbc_radio_wales_fm.isml/bbc_radio_wales_fm-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio Wiltshire", url: "http://as-hls-ww-live.akamaized.net/pool_44240917/live/ww/bbc_radio_wiltshire/bbc_radio_wiltshire.isml/bbc_radio_wiltshire-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio WM", url: "http://as-hls-ww-live.akamaized.net/pool_05353924/live/ww/bbc_wm/bbc_wm.isml/bbc_wm-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Radio York", url: "http://as-hls-ww-live.akamaized.net/pool_90848428/live/ww/bbc_radio_york/bbc_radio_york.isml/bbc_radio_york-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },
    { name: "BBC - Three Counties Radio", url: "http://as-hls-ww-live.akamaized.net/pool_69997923/live/ww/bbc_three_counties_radio/bbc_three_counties_radio.isml/bbc_three_counties_radio-audio%3d96000.norewind.m3u8", logo: "https://radio.baipon.com/img/radio/bbc.ico", category: "欧洲" },

    { name: "Rock Antenne (德国摇滚)", url: "https://mp3channels.webradio.antenne.de/rockantenne", logo: "https://www.rockantenne.de/favicon.ico", category: "网络音乐"},
    { name: "Klassik Radio (德国古典)", url: "http://edge.live.mp3.mdn.newmedia.nacamar.net/klassikradio128/livestream.mp3", logo: "https://www.klassikradio.de/favicon.ico", category: "网络音乐" },
    { name: "Radio 10 (荷兰经典流行)", url: "https://stream.radio10.nl/radio10", logo: "https://www.radio10.nl/favicon.ico",  category: "网络音乐" },
    { name: "Hot Hitz Radio (美国劲爆流行)", url: "https://hothitzradio.com/stream.mp3", logo: "https://hothitzradio.com/favicon.ico", category: "网络音乐" },
    { name: "181.FM Kickin' Country", url: "http://relay.181.fm:8130", logo: "https://www.181.fm/favicon.ico", category: "网络音乐" },
    { name: "181.FM Highway 181", url: "http://relay.181.fm:8018", logo: "https://www.181.fm/favicon.ico", category: "网络音乐" },
    { name: "181.FM 90's Country", url: "http://relay.181.fm:8050", logo: "https://www.181.fm/favicon.ico", category: "网络音乐" },
    { name: "Nashville FM WNXP(纳什维尔)", url: "https://wpln.streamguys1.com/wnxpfm.aac", logo: "https://wnxp.org/wp-content/uploads/2025/06/cropped-logo-just-letters-300x300.png", category: "网络音乐" },
    { name: "Country 108 (德国网络音乐台)", url: "http://www.country108.com/listen.m3u", logo: "https://www.country108.com/favicon.png.pagespeed.ce.tuEDsXNmeM.png", category: "网络音乐" },
    { name: "Truckers.FM (全球卡车社区)", url: "https://live.truckers.fm/", logo: "https://truckers.fm/favicon.ico", category: "网络音乐" },
    { name: "BigRigFM (卡车乡村音乐专用)", url: "https://radio.bigrig.fm/", logo: "https://bigrig.fm/favicon.ico", category: "网络音乐" },
    { name: "Simulator Radio (模拟飞行与卡车)", url: "https://stream.simulatorradio.com/stream.mp3", logo: "https://www.simulatorradio.com/favicon.ico", category: "网络音乐" },

    // ===内地地方===
    { name: "北京城市广播 (Beijing Public Service Radio)", url: "https://brtv-radiolive.rbc.cn/alive/fm1073.m3u8", logo: "https://radio.baipon.com/img/radio/btv.ico", category: "内地" },
    { name: "北京房山经典音乐 FM96.9 (Beijing Fangshan Classic Music)", url: "http://ls.qingting.fm/live/2131011.m3u8", logo: "https://radio.baipon.com/img/radio/btv.ico", category: "内地" },
    { name: "北京交通广播 (Beijing Traffic Radio)", url: "https://brtv-radiolive.rbc.cn/alive/fm1039.m3u8", logo: "https://radio.baipon.com/img/radio/btv.ico", category: "内地" },
    { name: "北京经典调频 (Beijing Classic FM)", url: "http://live.funhillrm.com/4/sd/live.m3u8", logo: "https://radio.baipon.com/img/radio/btv.ico", category: "内地" },
    { name: "北京文艺广播 FM87.6 (Beijing Literature & Art Radio)", url: "https://brtv-radiolive.rbc.cn/alive/fm876.m3u8", logo: "https://radio.baipon.com/img/radio/btv.ico", category: "内地" },
    { name: "北京新闻广播 (Beijing News Radio)", url: "https://brtv-radiolive.rbc.cn/alive/fm945.m3u8", logo: "https://radio.baipon.com/img/radio/btv.ico", category: "内地" },
    { name: "北京音乐广播 (Beijing Music Radio)", url: "https://brtv-radiolive.rbc.cn/alive/fm974.m3u8", logo: "https://radio.baipon.com/img/radio/btv.ico", category: "内地" },
    { name: "北京体育广播 (Beijing Sports Radio)", url: "https://brtv-radiolive.rbc.cn/alive/fm1025.m3u8", logo: "https://radio.baipon.com/img/radio/btv.ico", category: "内地" },
    { name: "安徽交通广播 Anhui Traffic", url: "https://satellitepull.cnr.cn/live/wxahjtgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/ahtv.ico", category: "内地" },
    { name: "安徽经济广播 Anhui Biz", url: "https://satellitepull.cnr.cn/live/wxahjjgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/ahtv.ico", category: "内地" },
    { name: "安徽旅游广播 Anhui Travel", url: "https://satellitepull.cnr.cn/live/wxahlygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/ahtv.ico", category: "内地" },
    { name: "安徽农村广播 Anhui Rural", url: "https://satellitepull.cnr.cn/live/wxahncgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/ahtv.ico", category: "内地" },
    { name: "安徽生活广播 Anhui Living", url: "https://satellitepull.cnr.cn/live/wxahshgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/ahtv.ico", category: "内地" },
    { name: "安徽戏曲广播 Anhui Opera", url: "https://satellitepull.cnr.cn/live/wxahxqgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/ahtv.ico", category: "内地" },
    { name: "安徽小说评书 Anhui Novel Storytelling", url: "https://satellitepull.cnr.cn/live/wxahxspsgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/ahtv.ico", category: "内地" },
    { name: "安徽音乐广播 Anhui Music", url: "https://satellitepull.cnr.cn/live/wxahyygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/ahtv.ico", category: "内地" },
    { name: "安徽之声 Voice of Anhui", url: "https://satellitepull.cnr.cn/live/wxahxxgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/ahtv.ico", category: "内地" },
    { name: "广东城市之声 Voice of City Guangdong", url: "https://satellitepull.cnr.cn/live/wxgdcszs/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/gdtv.ico", category: "内地" },
    
    { name: "广东股市广播 Guangdong Stock Market Radio", url: "https://satellitepull.cnr.cn/live/wxgdgsgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/gdtv.ico", category: "内地" },
    { name: "广东南方生活广播 FM93.6", url: "http://live.xmcdn.com/live/249/64.m3u8", logo: "https://radio.baipon.com/img/radio/gdtv.ico", category: "内地" },
    { name: "广东南粤之声", url: "https://satellitepull.cnr.cn/live/wxnyzs/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/gdtv.ico", category: "内地" },
    { name: "广东文体广播", url: "https://satellitepull.cnr.cn/live/wxgdwtgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/gdtv.ico", category: "内地" },
    { name: "广东新闻广播 FM91.4", url: "https://satellitepull.cnr.cn/live/wxgdxwgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/gdtv.ico", category: "内地" },
    { name: "广东羊城交通广播 FM105.2", url: "http://live.xmcdn.com/live/248/64.m3u8", logo: "https://radio.baipon.com/img/radio/gdtv.ico", category: "内地" },
    { name: "广东音乐之声 FM99.3", url: "https://satellitepull.cnr.cn/live/wxgdyyzs/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/gdtv.ico", category: "内地" },
    { name: "广东优悦广播(南粤) FM105.7", url: "http://ls.qingting.fm/live/470.m3u8", logo: "https://radio.baipon.com/img/radio/gdtv.ico", category: "内地" },
    { name: "广东珠江经济台 FM97.4", url: "http://live.xmcdn.com/live/252/64.m3u8", logo: "https://radio.baipon.com/img/radio/gdtv.ico", category: "内地" },
    { name: "广州 MYFM 88.0 都市生活", url: "http://ls.qingting.fm/live/52712.m3u8", logo: "https://radio.baipon.com/img/radio/gzb.ico", category: "内地" },
    { name: "广州花都广播 Canton Huadu Radio", url: "http://ls.qingting.fm/live/1263.m3u8", logo: "https://radio.baipon.com/img/radio/gzb.ico", category: "内地" },
    { name: "广州交通广播 Canton Traffic", url: "http://ls.qingting.fm/live/4955.m3u8", logo: "https://radio.baipon.com/img/radio/gzb.ico", category: "内地" },
    { name: "广州汽车音乐电台 Car Music Radio", url: "http://live.xmcdn.com/live/257/64.m3u8", logo: "https://radio.baipon.com/img/radio/gzb.ico", category: "内地" },
    { name: "福建财经961 (Fujian Finance Radio 961)", url: "https://satellitepull.cnr.cn/live/wx32fjdnjjgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/fjtv.ico", category: "内地" },
    { name: "福建东南广播 (Fujian Southeast Radio)", url: "https://satellitepull.cnr.cn/live/wx32fjdngb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/fjtv.ico", category: "内地" },
    { name: "福建都市广播 (Fujian City Radio)", url: "https://satellitepull.cnr.cn/live/wx32fjdndsgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/fjtv.ico", category: "内地" },
    { name: "福建交通广播 (Fujian Traffic Radio)", url: "https://satellitepull.cnr.cn/live/wx32fjdnjtgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/fjtv.ico", category: "内地" },
    { name: "福建经济广播 FM96.1 (Fujian Economy Radio)", url: "http://live.xmcdn.com/live/789/64.m3u8", logo: "https://radio.baipon.com/img/radio/fjtv.ico", category: "内地" },
    { name: "福建汽车音乐 (Fujian Auto Music Radio)", url: "https://satellitepull.cnr.cn/live/wx32fjdnyygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/fjtv.ico", category: "内地" },
    { name: "福建私家车广播 FM98.7 (Fujian Private Car Radio)", url: "http://live.xmcdn.com/live/793/64.m3u8", logo: "https://radio.baipon.com/img/radio/fjtv.ico", category: "内地" },
    { name: "福建新闻广播 (Fujian News Radio)", url: "https://satellitepull.cnr.cn/live/wx32fjxwgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/fjtv.ico", category: "内地" },
    { name: "福建音乐广播 FM91.3 (Fujian Music Radio)", url: "http://ls.qingting.fm/live/4585.m3u8", logo: "https://radio.baipon.com/img/radio/fjtv.ico", category: "内地" },
    { name: "厦门音乐广播 FM90.9 (Xiamen Music Radio)", url: "https://ytcast.radio.cn/74/radios/21897/index_21897.m3u8?type=1&key=9df9e9899a57eea311ee51d6a6262cb3&time=6a008482", logo: "https://radio.baipon.com/img/radio/xiamen.ico", category: "内地" },
    { name: "海南音乐广播 Hainan Music", url: "https://satellitepull.cnr.cn/live/wxhainyygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/hnmusic.ico", category: "内地" },
    { name: "广西北部湾之声 Beibu Gulf Radio", url: "https://stream.bbrtv.com:10443/hls/_6ax4Y1MR/_6ax4Y1MR_live.m3u8", logo: "https://radio.baipon.com/img/radio/gxtv.ico", category: "内地" },
    { name: "广西交通广播 Guangxi Traffic", url: "https://stream.bbrtv.com:10443/hls/scGbVLJGR/scGbVLJGR_live.m3u8", logo: "https://radio.baipon.com/img/radio/gxtv.ico", category: "内地" },
    { name: "广西经济广播（女主播电台） Guangxi Female Host Radio", url: "https://stream.bbrtv.com:10443/hls/wrr24LJGR/wrr24LJGR_live.m3u8", logo: "https://radio.baipon.com/img/radio/gxtv.ico", category: "内地" },
    { name: "广西私家车930 教育广播", url: "https://stream.bbrtv.com:10443/hls/I7LJVL1Gg/I7LJVL1Gg_live.m3u8", logo: "https://radio.baipon.com/img/radio/gxtv.ico", category: "内地" },
    { name: "广西文艺广播 Guangxi Music", url: "https://stream.bbrtv.com:10443/hls/rCjJ4Y1MR/rCjJ4Y1MR_live.m3u8", logo: "https://radio.baipon.com/img/radio/gxtv.ico", category: "内地" },
    { name: "广西新闻910 Guangxi News", url: "https://stream.bbrtv.com:10443/hls/sIoyCf1Gg/sIoyCf1Gg_live.m3u8", logo: "https://radio.baipon.com/img/radio/gxtv.ico", category: "内地" },
    
    { name: "上海东方广播 Shanghai East Radio", url: "https://satellitepull.cnr.cn/live/wx32dfgbdt/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/smg.ico", category: "内地" },
    { name: "上海新闻广播 Shanghai News Radio", url: "https://satellitepull.cnr.cn/live/wx32shrmgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/smg.ico", category: "内地" },
    { name: "上海动感101 Shanghai FM101", url: "https://ytcast.radio.cn/64/radios/21311/index_21311.m3u8?type=1&key=22dd7c4e685bf3fc9ae69703acb33d27&time=6a002f32", logo: "https://radio.baipon.com/img/radio/smg.ico", category: "内地" },
    { name: "上海流行音乐 Love Radio", url: "https://ytcast.radio.cn/64/radios/21313/index_21313.m3u8?type=1&key=62206c363d23c334a9581f56f89ff9d2&time=6a000eea", logo: "https://radio.baipon.com/img/radio/smg.ico", category: "内地" },
    
    { name: "深圳飞扬971", url: "https://satellitepull.cnr.cn/live/wxszfy971/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/szmg.ico", category: "内地" },
    { name: "深圳交通频率", url: "https://satellitepull.cnr.cn/live/wxszjjpl/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/szmg.ico", category: "内地" },
    { name: "深圳快乐1062(交通广播)", url: "http://ls.qingting.fm/live/1272.m3u8", logo: "https://radio.baipon.com/img/radio/szmg.ico", category: "内地" },
    { name: "深圳私家车", url: "https://satellitepull.cnr.cn/live/wxszsjcgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/szmg.ico", category: "内地" },

    { name: "新疆哈语广播 (Xinjiang Kazakh Radio)", url: "https://satellitepull.cnr.cn/live/wxxjhygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xjtv.ico", category: "内地" },
    { name: "新疆交通广播 (Xinjiang Traffic Radio)", url: "https://satellitepull.cnr.cn/live/wxxjjtgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xjtv.ico", category: "内地" },
    { name: "新疆柯尔克孜语广播 (Xinjiang Kyrgyz Radio)", url: "https://satellitepull.cnr.cn/live/wxxjkygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xjtv.ico", category: "内地" },
    { name: "新疆绿色广播 (Xinjiang Green Radio)", url: "https://satellitepull.cnr.cn/live/wxxjlsgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xjtv.ico", category: "内地" },
    { name: "新疆蒙语广播 (Xinjiang Mongolian Radio)", url: "https://satellitepull.cnr.cn/live/wxxjmygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xjtv.ico", category: "内地" },
    { name: "新疆私家车广播 (Xinjiang Private Car Radio)", url: "https://satellitepull.cnr.cn/live/wxxjsjcgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xjtv.ico", category: "内地" },
    { name: "新疆维吾尔语交通文艺广播 (Xinjiang Uyghur Traffic & Arts Radio)", url: "https://satellitepull.cnr.cn/live/wxxjwyjtwygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xjtv.ico", category: "内地" },
    { name: "新疆维语综合广播 (Xinjiang Uyghur Comprehensive Radio)", url: "https://satellitepull.cnr.cn/live/wxxjwyzhgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xjtv.ico", category: "内地" },
    { name: "新疆新闻广播 (Xinjiang News Radio)", url: "https://satellitepull.cnr.cn/live/wxxjxwgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xjtv.ico", category: "内地" },
    { name: "辽宁交通广播 Liaoning Traffic", url: "https://satellitepull.cnr.cn/live/wxlnjtgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/lntv.ico", category: "内地" },
    { name: "辽宁经济广播 Liaoning Economy", url: "https://satellitepull.cnr.cn/live/wxlnjjtb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/lntv.ico", category: "内地" },
    { name: "辽宁文艺广播 Liaoning Arts", url: "https://satellitepull.cnr.cn/live/wxlnwygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/lntv.ico", category: "内地" },
    { name: "辽宁乡村广播 Liaoning Rural", url: "https://satellitepull.cnr.cn/live/wxlnxcgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/lntv.ico", category: "内地" },
    { name: "辽宁之声 Voice of Liaoning", url: "https://satellitepull.cnr.cn/live/wxlnzhgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/lntv.ico", category: "内地" },
    { name: "重庆都市广播", url: "https://satellitepull.cnr.cn/live/wxcqdsgb/playlist.m3u8", logo: "", category: "内地" },
    { name: "重庆交通广播", url: "https://satellitepull.cnr.cn/live/wxcqjtgb/playlist.m3u8", logo: "", category: "内地" },
    { name: "重庆新闻广播", url: "https://satellitepull.cnr.cn/live/wxcqxwgb/playlist.m3u8", logo: "", category: "内地" },
    { name: "重庆音乐广播", url: "https://satellitepull.cnr.cn/live/wxcqyygb/playlist.m3u8", logo: "", category: "内地" },
    { name: "珠海电台交通音乐875", url: "http://ls.qingting.fm/live/1275.m3u8", logo: "https://radio.baipon.com/img/radio/zhtv.ico", category: "内地" },
    { name: "珠海电台先锋951", url: "http://ls.qingting.fm/live/1274.m3u8", logo: "https://radio.baipon.com/img/radio/zhtv.ico", category: "内地" },
    { name: "浙江财富广播 FM95", url: "http://ls.qingting.fm/live/4519.m3u8", logo: "https://radio.baipon.com/img/radio/zjtv.ico", category: "内地" },
    { name: "浙江城市之声", url: "https://satellitepull.cnr.cn/live/wxzjcszs/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/zjtv.ico", category: "内地" },
    { name: "浙江动听(音乐调频) FM96.8", url: "http://ls.qingting.fm/live/4866.m3u8", logo: "https://radio.baipon.com/img/radio/zjtv.ico", category: "内地" },
    { name: "浙江交通之声", url: "https://satellitepull.cnr.cn/live/wxzjjtgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/zjtv.ico", category: "内地" },
    { name: "浙江经济广播", url: "https://satellitepull.cnr.cn/live/wxzjjjgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/zjtv.ico", category: "内地" },
    { name: "浙江民生996", url: "https://satellitepull.cnr.cn/live/wxzjmsgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/zjtv.ico", category: "内地" },
    { name: "浙江女主播电台", url: "https://satellitepull.cnr.cn/live/wxzj1045/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/zjtv.ico", category: "内地" },
    { name: "浙江悦动之音", url: "https://satellitepull.cnr.cn/live/wxzj968/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/zjtv.ico", category: "内地" },
    { name: "浙江之声", url: "https://satellitepull.cnr.cn/live/wxzjzs/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/zjtv.ico", category: "内地" },
    { name: "西藏藏语广播 Tibet Tibetan Radio", url: "https://satellitepull.cnr.cn/live/wxxzzygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xztv.ico", category: "内地" },
    { name: "西藏藏语康巴方言 Tibet Kham Tibetan", url: "https://satellitepull.cnr.cn/live/wxxzzykbfy/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xztv.ico", category: "内地" },
    { name: "西藏都市生活 Tibet City Radio", url: "https://satellitepull.cnr.cn/live/wxxzdsshgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xztv.ico", category: "内地" },
    { name: "西藏对外交通 Tibet Traffic Radio", url: "https://satellitepull.cnr.cn/live/wxxzdwjtgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xztv.ico", category: "内地" },
    { name: "西藏汉语广播 Tibet Mandarin Radio", url: "https://satellitepull.cnr.cn/live/wxxzhygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/xztv.ico", category: "内地" },
    { name: "江苏财经广播 (Jiangsu Finance Radio)", url: "https://satellitepull.cnr.cn/live/wx32jscjgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jstv.ico", category: "内地" },
    { name: "江苏故事广播 (Jiangsu Story Radio)", url: "https://satellitepull.cnr.cn/live/wx32jsgsgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jstv.ico", category: "内地" },
    { name: "江苏健康广播 (Jiangsu Health Radio)", url: "https://satellitepull.cnr.cn/live/wx32jsjkgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jstv.ico", category: "内地" },
    { name: "江苏交通广播 (Jiangsu Traffic Radio)", url: "https://satellitepull.cnr.cn/live/wx32jsjtgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jstv.ico", category: "内地" },
    { name: "江苏金陵之声 (Jiangsu Voice Of Jinling)", url: "https://satellitepull.cnr.cn/live/wx32jsqctp/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jstv.ico", category: "内地" },
    { name: "江苏经典流行音乐 (Jiangsu Classic Pop Music)", url: "https://satellitepull.cnr.cn/live/wx32jsjdlxyy/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jstv.ico", category: "内地" },
    { name: "江苏文艺广播 (Jiangsu Literature & Art Radio)", url: "https://satellitepull.cnr.cn/live/wx32jswygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jstv.ico", category: "内地" },
    { name: "江苏新闻广播 (Jiangsu News Radio)", url: "https://satellitepull.cnr.cn/live/wx32jsxwgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jstv.ico", category: "内地" },
    { name: "江苏音乐广播 (Jiangsu Music Radio)", url: "https://satellitepull.cnr.cn/live/wx32jsyygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jstv.ico", category: "内地" },
    { name: "江西都市广播 (Jiangxi City Radio)", url: "https://satellitepull.cnr.cn/live/wx32jiangxdsgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jxtv.ico", category: "内地" },
    { name: "江西交通广播 (Jiangxi Traffic Radio)", url: "https://satellitepull.cnr.cn/live/wx32jiangxjtgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jxtv.ico", category: "内地" },
    { name: "江西民生广播 (Jiangxi Livelihood Radio)", url: "https://satellitepull.cnr.cn/live/wx32jiangxmsgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jxtv.ico", category: "内地" },
    { name: "江西农村广播 (Jiangxi Rural Radio)", url: "https://satellitepull.cnr.cn/live/wx32jiangxncgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jxtv.ico", category: "内地" },
    { name: "江西新闻广播 (Jiangxi News Radio)", url: "https://satellitepull.cnr.cn/live/wx32jiangxxwgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jxtv.ico", category: "内地" },
    { name: "江西音乐广播 (Jiangxi Music Radio)", url: "https://satellitepull.cnr.cn/live/wx32jiangxyygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/jxtv.ico", category: "内地" },
    { name: "湖南交通广播 (Hunan Traffic Radio)", url: "https://satellitepull.cnr.cn/live/wx32hunjtgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/hntv.ico", category: "内地" },
    { name: "湖南金鹰之声 (Hunan Golden Eagle Voice)", url: "https://satellitepull.cnr.cn/live/wx32955/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/hntv.ico", category: "内地" },
    { name: "湖南经济广播 (Hunan Economy Radio)", url: "https://satellitepull.cnr.cn/live/wx32hunjjgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/hntv.ico", category: "内地" },
    { name: "湖南893芒果音乐台 (Hunan Music Radio)", url: "https://satellitepull.cnr.cn/live/wx32hunyygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/hntv.ico", category: "内地" },
    { name: "湖南潇湘之声 (Hunan Xiaoxiang Voice)", url: "https://satellitepull.cnr.cn/live/wx32hunyygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/hntv.ico", category: "内地" },
    { name: "湖南新闻广播 (Hunan News Radio)", url: "https://satellitepull.cnr.cn/live/wx32hunxwgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/hntv.ico", category: "内地" },
    { name: "内蒙古音乐之声 Inner Mongolia Music", url: "https://satellitepull.cnr.cn/live/wx32nmgyygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/nmtv.ico", category: "内地" },
    { name: "内蒙古交通之声 Inner Mongolia Traffic", url: "https://satellitepull.cnr.cn/live/wx32nmgjtgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/nmtv.ico", category: "内地" },
    { name: "内蒙古对外广播 Inner Mongolia External", url: "https://satellitepull.cnr.cn/live/wx32nmgdwgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/nmtv.ico", category: "内地" },
    { name: "内蒙古汉语广播 Inner Mongolia Mandarin", url: "https://satellitepull.cnr.cn/live/wx32nmghyzhxwgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/nmtv.ico", category: "内地" },
    { name: "内蒙古经济生活 Inner Mongolia Economy & Life", url: "https://satellitepull.cnr.cn/live/wx32nmgjjgb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/nmtv.ico", category: "内地" },
    { name: "内蒙古绿野之声 Green Field Radio", url: "https://satellitepull.cnr.cn/live/wx32nmglyzs/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/nmtv.ico", category: "内地" },
    { name: "内蒙古蒙古语广播 Inner Mongolia Mongolian", url: "https://satellitepull.cnr.cn/live/wx32nmgmygb/playlist.m3u8", logo: "https://radio.baipon.com/img/radio/nmtv.ico", category: "内地" }
];

console.log("Loaded at" + new Date().getTime());
