/**
 * 电台数据配置 - 百品专用
 */
var radioStations = [
    // === 香港 ===
    { name: "香港电台第一台", url: "https://rthkaudio1-lh.akamaihd.net/i/radio1_1@355864/master.m3u8", logo: "https://www.rthk.hk/favicon.ico", category: "香港" },
    { name: "香港电台第二台", url: "https://rthkaudio2-lh.akamaihd.net/i/radio2_1@355865/master.m3u8", logo: "https://www.rthk.hk/favicon.ico", category: "香港" },
    { name: "香港电台第三台", url: "https://rthkaudio3-lh.akamaihd.net/i/radio3_1@355866/master.m3u8", logo: "https://www.rthk.hk/favicon.ico", category: "香港" },
    { name: "香港电台第四台 (古典音乐)", url: "https://rthkaudio4-lh.akamaihd.net/i/radio4_1@355867/master.m3u8", logo: "https://www.rthk.hk/favicon.ico", category: "香港" },
    { name: "香港电台第五台", url: "https://rthkaudio5-lh.akamaihd.net/i/radio5_1@355868/master.m3u8", logo: "https://www.rthk.hk/favicon.ico", category: "香港" },
    { name: "香港电台第六台转播香港之声", url: "https://rthkradiocnrhk-live.akamaized.net/hls/live/2046111/radiocnrhk/master.m3u8", logo: "https://www.rthk.hk/favicon.ico", category: "香港" },
    { name: "香港电台普通话台", url: "https://rthkaudio6-lh.akamaihd.net/i/radiopth_1@355869/master.m3u8", logo: "https://www.rthk.hk/favicon.ico", category: "香港" },
    { name: "香港电台转播大湾区之声", url: "https://rthkradiocmgrgb-live.akamaized.net/hls/live/2046112/radiocmgrgb/index_64_a.m3u8", logo: "https://www.rthk.hk/favicon.ico", category: "香港" },

    { name: "新城知讯台 (997)", url: "https://metroradio-lh.akamaihd.net/i/997_h@349799/master.m3u8", logo: "https://www.metroradio.com.hk/favicon.ico", category: "香港" },
    { name: "新城财经台 (104)", url: "https://metroradio-lh.akamaihd.net/i/104_h@349798/master.m3u8", logo: "https://www.metroradio.com.hk/favicon.ico", category: "香港" },
    { name: "新城采讯台 (Metro Plus AM1044)", url: "https://metroradio-lh.akamaihd.net/i/1044_h@349800/master.m3u8", logo: "https://www.metroradio.com.hk/favicon.ico", category: "香港" },

    { name: "雷霆881 商业一台", url: "https://d2agljdoug3z0j.cloudfront.net/radio-HTTP/cr1-hd.3gp/chunklist.m3u8", logo: "https://www.881903.com/favicon.ico", category: "香港" },
    { name: "叱咤903 商业二台", url: "https://d2agljdoug3z0j.cloudfront.net/radio-HTTP/cr2-hd.3gp/chunklist.m3u8", logo: "https://www.881903.com/favicon.ico", category: "香港" },
    { name: "豁达864", url: "https://d3ca3xccq5z5hu.cloudfront.net/radio-HTTP/am864.3gp/chunklist.m3u8", logo: "https://www.881903.com/favicon.ico", category: "香港" },

    // === 澳门 ===
    { name: "澳门电台 (中文)", url: "https://live5.tdm.com.mo/live/rch2.live/playlist.m3u8", logo: "https://cdn2.tdm.com.mo/uploads/media/web_images/tdm new app logo.png", category: "澳门" },
    { name: "澳门电台 (葡文)", url: "https://live5.tdm.com.mo/live/rch1.live/playlist.m3u8", logo: "https://cdn2.tdm.com.mo/uploads/media/web_images/tdm new app logo.png", category: "澳门" },
    { name: "绿邨电台", url: "https://fm995.ddns.net/hls1/fm995.m3u8", logo: "https://mfm995.com/wp-content/uploads/2022/09/cropped-icon20220930_1.png", category: "澳门" },

    // === 内地 (CNR / CMG / CRI) ===
    { name: "中国之声", url: "https://ngcdn001.cnr.cn/live/zgzs/index.m3u8", logo: "img/radio/cnr.jpg", category: "内地" },
    { name: "经济之声", url: "https://ngcdn002.cnr.cn/live/jjzs/index.m3u8", logo: "img/radio/cnr.jpg", category: "内地" },
    { name: "音乐之声", url: "https://ngcdn003.cnr.cn/live/yyzs/index.m3u8", logo: "img/radio/cnr.jpg", category: "内地" },
    { name: "经典音乐广播", url: "https://ngcdn004.cnr.cn/live/dszs/index.m3u8", logo: "img/radio/cnr.jpg", category: "内地" },
    { name: "中华之声", url: "https://ngcdn005.cnr.cn/live/zhzs/index.m3u8", logo: "img/radio/cnr.jpg", category: "内地" },
    { name: "神州之声", url: "https://ngcdn006.cnr.cn/live/szzs/index.m3u8", logo: "img/radio/cnr.jpg", category: "内地" },
    { name: "大湾区之声", url: "https://ngcdn007.cnr.cn/live/hxzs/index.m3u8", logo: "img/radio/cnr.jpg", category: "内地" },
    { name: "香港之声", url: "https://ngcdn008.cnr.cn/live/xgzs/index.m3u8", logo: "img/radio/cnr.jpg", category: "内地" },
    { name: "民族之声", url: "https://ngcdn009.cnr.cn/live/mzzs/index.m3u8", logo: "img/radio/cnr.jpg", category: "内地" },
    { name: "文艺之声", url: "https://ngcdn010.cnr.cn/live/wyzs/index.m3u8", logo: "img/radio/cnr.jpg", category: "内地" },
    { name: "阅读之声", url: "https://ngcdn014.cnr.cn/live/ylgb/index.m3u8", logo: "img/radio/cnr.jpg", category: "内地" },
    { name: "中国交通广播", url: "https://ngcdn016.cnr.cn/live/gsgljtgb/index.m3u8", logo: "img/radio/cnr.jpg", category: "内地" },
    { name: "中国网络音乐之声", url: "https://ngcdn017.cnr.cn/live/xczs/index.m3u8", logo: "img/radio/cnr.jpg", category: "内地" },

    { name: "华语环球广播 (CRI)", url: "http://sk.cri.cn/hyhq.m3u8", logo: "https://www.cri.cn/favicon.ico", category: "内地" },
    { name: "环球资讯广播", url: "http://sk.cri.cn/905.m3u8", logo: "https://www.cri.cn/favicon.ico", category: "内地" },
    { name: "英语资讯广播 (China Plus)", url: "http://cnlive.cnr.cn/hls/yyzxgb.m3u8", logo: "https://www.cri.cn/favicon.ico", category: "内地" },
    { name: "世界华声", url: "http://sk.cri.cn/hxfh.m3u8", logo: "https://www.cri.cn/favicon.ico", category: "内地" },
    { name: "劲曲调频 (CRI Hit FM)", url: "http://sk.cri.cn/887.m3u8", logo: "https://www.cri.cn/favicon.ico", category: "内地" },
    { name: "轻松调频 (CRI EZFM)", url: "http://sk.cri.cn/915.m3u8", logo: "https://www.cri.cn/favicon.ico", category: "内地" },

    // === 台湾 ===
    // 警察广播电台（含补充分台）
    { name: "警察广播电台 全国治安交通网", url: "https://stream.pbs.gov.tw/live/PBS/playlist.m3u8", logo: "img/radio/pbs.jpg", category: "台湾" },
    { name: "警察广播电台 台北分台", url: "https://stream.pbs.gov.tw/live/TPS/playlist.m3u8", logo: "img/radio/pbs.jpg", category: "台湾" },
    { name: "警察广播电台 台中分台", url: "https://stream.pbs.gov.tw/live/TCS/playlist.m3u8", logo: "img/radio/pbs.jpg", category: "台湾" },
    { name: "警察广播电台 台南分台", url: "https://stream.pbs.gov.tw/live/TNS/playlist.m3u8", logo: "img/radio/pbs.jpg", category: "台湾" },
    { name: "警察广播电台 高雄分台", url: "https://stream.pbs.gov.tw/live/KSS/playlist.m3u8", logo: "img/radio/pbs.jpg", category: "台湾" },
    { name: "警察广播电台 宜兰分台", url: "https://stream.pbs.gov.tw/live/ELS/playlist.m3u8", logo: "img/radio/pbs.jpg", category: "台湾" },
    { name: "警察广播电台 花莲分台", url: "https://stream.pbs.gov.tw/live/HLS/playlist.m3u8", logo: "img/radio/pbs.jpg", category: "台湾" },
    { name: "警察广播电台 台东分台", url: "http://stream.pbs.gov.tw:1935/live/TTS/playlist.m3u8", logo: "img/radio/pbs.jpg", category: "台湾" },
    { name: "警察广播电台 新竹分台", url: "http://stream.pbs.gov.tw:1935/live/SCS/playlist.m3u8", logo: "img/radio/pbs.jpg", category: "台湾" },

    // 中央广播电台 (RTI)
    { name: "中央广播电台 国语台 (RTI)", url: "https://streamak0138.akamaized.net/live0138lh-mbm9/_definst_/rti3/playlist.m3u8", logo: "https://www.rti.org.tw/favicon.ico", category: "台湾" },
    { name: "中央广播电台 音乐台 (RTI)", url: "http://live2.rti.org.tw/live/_definst_/rti/rti4/playlist.m3u8", logo: "https://www.rti.org.tw/favicon.ico", category: "台湾" },
    { name: "中央广播电台 讲客电台 (RTI Hakka)", url: "http://live2.rti.org.tw/live/_definst_/rti/hakka/playlist.m3u8", logo: "https://www.rti.org.tw/favicon.ico", category: "台湾" },

    // 其他台湾电台（含补充）
    { name: "ICRT 台北国际社区广播电台", url: "https://stream.rcs.revma.com/nkdfurztxp3vv", logo: "https://www.icrt.com.tw/favicon.ico", category: "台湾" },
    { name: "BravoFM 台北都会音乐台", url: "https://onair.bravo913.com.tw:9130/live.mp3", logo: "", category: "台湾" },
    { name: "CityFM 台中城市广播 (929)", url: "http://fm929.cityfm.tw:8080/929.mp3", logo: "img/radio/cityfm.webp", category: "台湾" },
    { name: "CityFM 台北健康电台 (901)", url: "http://fm901.cityfm.tw:8080/901.mp3", logo: "img/radio/cityfm.webp", category: "台湾" },
    { name: "CityFM 大苗栗 (983)", url: "http://fm983.cityfm.tw:8080/983.mp3", logo: "img/radio/cityfm.webp", category: "台湾" },
    { name: "CityFM 台南知音 (971)", url: "http://fm971.cityfm.tw:8080/971.mp3", logo: "img/radio/cityfm.webp", category: "台湾" },
    { name: "M-Radio 全国", url: "http://stream.rcs.revma.com/044q61ha7a0uv", logo: "https://www.mradio.com.tw/favicon.ico", category: "台湾" },

    { name: "Classical FM 97.7", url: "https://onair.family977.com.tw:8977/live.mp3", logo: "img/radio/classical.jpg", category: "台湾" },
    { name: "BravoFM 91.3台北都会音乐台", url: "https://onair.bravo913.com.tw:9130/live.mp3", logo: "https://www.bravo913.com.tw/lazyweb/images/logo.png", category: "台湾" },
    { name: "ICRT", url: "https://stream.rcs.revma.com/nkdfurztxp3vv", logo: "https://www.icrt.com.tw/favicon.ico", category: "台湾" },
    { name: "News 98", url: "https://stream.rcs.revma.com/pntx1639ntzuv.m4a", logo: "http://www.news98.com.tw/images/neil.ico", category: "台湾" },
    { name: "IC之音 竹科廣播電台", url: "https://stream.rcs.revma.com/7mnq8rt7k5zuv", logo: "https://www.ic975.com/favicon.svg", category: "台湾" },
    { name: "臺北廣播電臺93.1", url: "https://stream.ginnet.cloud/live0130lo-yfyo/_definst_/fm/playlist.m3u8", logo: "img/radio/tr.jpg", category: "台湾" },
    { name: "中廣流行網", url: "https://sonnykuo.appspot.com/bcc/?id=中廣流行網", logo: "https://www.bcc.com.tw/images/bcc.ico", category: "台湾" },
    { name: "中廣音樂網", url: "https://sonnykuo.appspot.com/bcc/?id=中廣音樂網", logo: "https://www.bcc.com.tw/images/bcc.ico", category: "台湾" },
    { name: "中廣新聞網", url: "https://sonnykuo.appspot.com/bcc/?id=中廣新聞網", logo: "https://www.bcc.com.tw/images/bcc.ico", category: "台湾" },
    { name: "中廣鄉親網", url: "https://sonnykuo.appspot.com/bcc/?id=中廣鄉親網", logo: "https://www.bcc.com.tw/images/bcc.ico", category: "台湾" },
    { name: "中廣I go 531", url: "https://sonnykuo.appspot.com/bcc/?id=I%20go%2020531", logo: "https://www.bcc.com.tw/images/bcc.ico", category: "台湾" },
    { name: "飛碟聯播網", url: "https://stream.rcs.revma.com/em90w4aeewzuv.m4a", logo: "https://www.uforadio.com.tw/frontend_assets/img/logo-s.png", category: "台湾" },
    { name: "AsiaFM 亞洲電台", url: "https://stream.rcs.revma.com/xpgtqc74hv8uv", logo: "https://www.asiafm.com.tw/wp-content/uploads/2023/03/logo-footer-04.png", category: "台湾" },
    { name: "AsiaFM 亚太电台 FM92.3", url: "https://stream.rcs.revma.com/kydend74hv8uv", logo: "https://www.asiafm.com.tw/wp-content/themes/asiafm/images/logo.png", category: "台湾" },
    { name: "AsiaFM 飞扬调频 FM89.5", url: "https://stream.rcs.revma.com/e0tdah74hv8uv", logo: "https://www.asiafm.com.tw/wp-content/themes/asiafm/images/logo.png", category: "台湾" },
    { name: "Hit FM 台北之音", url: "http://202.39.43.67:1935/live/RA000036/chunklist.m3u8", logo: "https://www.hitoradio.com/newweb/imgs/logo_2013.jpg", category: "台湾" },
    { name: "好事聯播網", url: "http://202.39.43.67:1935/live/RA000013/chunklist.m3u8", logo: "http://www.bestradio.com.tw/images/logo.png", category: "台湾" },
    { name: "台北流行廣播POP Radio", url: "http://202.39.43.67:1935/live/RA000080/chunklist.m3u8", logo: "https://www.pop917.com/images/logo_2025.png", category: "台湾" },
    { name: "台北愛樂电台", url: "http://202.39.43.67:1935/live/RA000018/chunklist.m3u8", logo: "https://www.e-classical.com.tw/img/favicon.ico", category: "台湾" },
    { name: "幸福电台 FM102.5", url: "http://61.218.61.251:8080", logo: "https://www.tr幸福广播.tw/favicon.ico", category: "台湾" },
    { name: "世新广播电台 88.1", url: "https://stream.ginnet.cloud/live0115lo-89xv/_definst_/fm881/playlist.m3u8", logo: "https://shrs.shu.edu.tw/wp-content/uploads/2021/04/logo.png", category: "台湾" },
    { name: "台艺之声 88.3", url: "https://votastream.ntua.edu.tw:8443/vota", logo: "https://vota.ntua.edu.tw/member/vota88_3/upload_file/vota88_3/461/16159474612.png", category: "台湾" },
    { name: "辅大之声 88.5", url: "http://fjuvoice885.fju.edu.tw:8000/fjuvoice885.mp3", logo: "https://www.fjucomm.com/fjuvoice885/wp-content/uploads/2017/07/logo%E7%99%BD%E5%B0%8F-01.png", category: "台湾" },
    { name: "政大之声 88.7", url: "http://vnccuonair.nccu.edu.tw:8000/ade.taiwan.mp3", logo: "https://vnccu.nccu.edu.tw/assets/images/style70/kv-small1.jpg", category: "台湾" },
    { name: "淡江之声 88.7", url: "http://163.13.182.81:8001/votk", logo: "img/radio/votk.jpg", category: "台湾" },
    { name: "铭传之声 88.3", url: "http://radio.mcu.edu.tw:8080/radio", logo: "http://radio.mcu.edu.tw/wp-content/uploads/2021/12/foot_pic_3-300x300-1.jpg", category: "台湾" },
    { name: "佳音Love联播网", url: "https://stream.ginnet.cloud/live0119lo-p4rb/_definst_/fm909/playlist.m3u8", logo: "http://www.goodnews.org.tw/favicon.ico", category: "台湾" },
    { name: "渔业广播电台", url: "https://stream.rcs.revma.com/mk0c5vq122hvv", logo: "img/radio/frs.jpg", category: "台湾" },
    { name: "正声综合台", url: "http://flv.ccdntech.com/live/_definst_/mp4:vod117_Live/live2/playlist.m3u8", logo: "https://www.csbc.com.tw/wp-content/uploads/2019/05/02.app%E5%8D%80%E5%A1%8A.png", category: "台湾" },
    { name: "正声 104.1", url: "http://flv.ccdntech.com/live/_definst_/mp4:vod117_Live/live1/playlist.m3u8", logo: "https://www.csbc.com.tw/wp-content/uploads/2019/05/02.app%E5%8D%80%E5%A1%8A.png", category: "台湾" },
    { name: "UNI FM96.7 环宇广播电台", url: "https://n10.rcs.revma.com/srn5f9kmwxhvv", logo: "img/radio/uni.png", category: "台湾" },
    { name: "汉声广播电台", url: "http://202.39.43.67:1935/live/RA000076/chunklist.m3u8", logo: "https://www.voh.com.tw/images/logo.png", category: "台湾" },
    { name: "国立教育广播电台/台北 101.7", url: "https://cast.ner.gov.tw/1", logo: "https://www.ner.gov.tw/icon.jpg", category: "台湾" },
        
    { name: "LOVE 972", url: "https://14033.live.streamtheworld.com/LOVE972FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/love-972.png", category: "新加坡" },
    { name: "YES 933", url: "https://22393.live.streamtheworld.com/YES933_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/yes-933.png", category: "新加坡" },
    { name: "CNA 938", url: "https://14033.live.streamtheworld.com/938NOW_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/cna-938.png", category: "新加坡" },
    { name: "CAPITAL 958", url: "https://19183.live.streamtheworld.com/CAPITAL958FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/capital-958.png", category: "新加坡" },
    { name: "CLASS 95", url: "https://14033.live.streamtheworld.com/CLASS95_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/class-95.png", category: "新加坡" },
    { name: "GOLD 905", url: "https://14033.live.streamtheworld.com/GOLD905_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/gold-905.png", category: "新加坡" },
    { name: "987FM", url: "https://14033.live.streamtheworld.com/987FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/987.png", category: "新加坡" },
    { name: "SYMPHONY 924", url: "https://14033.live.streamtheworld.com/SYMPHONY924FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/symphony-924.png", category: "新加坡" },
    { name: "RIA 897", url: "https://14033.live.streamtheworld.com/RIA897FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/ria-897.png", category: "新加坡" },
    { name: "Oli 968", url: "https://14033.live.streamtheworld.com/OLI968FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/oli-968.png", category: "新加坡" },
    { name: "Warna 942", url: "https://14033.live.streamtheworld.com/WARNA942FM_PREM.aac", logo: "https://www16.mediacorp.sg/melisten/radiostation-logos/warna-942.png", category: "新加坡" },
    { name: "UFM 100.3", url: "https://28093.live.streamtheworld.com/UFM_1003AAC.aac", logo: "https://www.ufm1003.sg/wp-content/assets/5/img/NAV_01_Logo_1003.svg", category: "新加坡" },
    { name: "96.3 好FM", url: "https://22243.live.streamtheworld.com/HAO_963AAC.aac", logo: "https://static.moneyfm893.sg/uploads/sites/7/2024/08/HaoFm-fullcolor-copy.svg", category: "新加坡" },
    { name: "One FM 91.3", url: "https://22283.live.streamtheworld.com/ONE_FM_913AAC.aac", logo: "https://www.onefm.sg/wp-content/assets/3/img/NAV_01_Logo_913-new.svg", category: "新加坡" },
    { name: "Kiss92 FM", url: "https://22283.live.streamtheworld.com/KISS_92AAC.aac", logo: "https://www.kiss92.sg/wp-content/assets/4/img/NAV_01_Logo_920.svg", category: "新加坡" },
    { name: "Power 98 Love Songs", url: "https://28093.live.streamtheworld.com/POWER98_LOVESONGS_SC", logo: "img/radio/power98.png", category: "新加坡" },

    // === 国际 / 其他 ===
    { name: "BBC World Service", url: "https://stream.live.vc.bbcmedia.co.uk/bbc_world_service", logo: "https://www.bbc.com/favicon.ico", category: "国际" },
    { name: "半岛电视台 (Al Jazeera English)", url: "https://live-hls-audio-web-aje.getaj.net/VOICE-AJE/01.m3u8", logo: "https://www.aljazeera.com/favicon.ico", category: "国际" },
    { name: "Linn Jazz (高音质)", url: "http://89.16.185.174:8004/stream", logo: "https://small.linncdn.com/website/responsive/images/favicon.ico", category: "国际" },
    { name: "NHK 世界广播 (中文)", url: "https://nhkworld.webcdn.stream.ne.jp/www11/radiojapan/all/263948/live_s.m3u8", logo: "https://www.nhk.or.jp/favicon.ico", category: "国际" },
    { name: "VOA Global English", url: "http://voa-ingest.akamaized.net/hls/live/2035200/161_352R/playlist.m3u8", logo: "https://www.voachinese.com/Content/responsive/VOA/zh-CN/img/logo.svg", category: "国际" },

    // === 网络音乐 ===
    { name: "V2BEAT", url: "https://stream.v2beat.live/icecast.audio?t=file.mp3", logo: "", category: "网络音乐" },
    { name: "AsiaFM 亚洲音乐", url: "http://asiafm.hk:8000/asiafm", logo: "", category: "网络音乐" },
    { name: "AsiaFM HD音乐", url: "http://asiafm.hk:8000/asiahd", logo: "", category: "网络音乐" },
    { name: "AsiaFM 亚洲经典", url: "http://goldfm.cn:8000/goldfm", logo: "", category: "网络音乐" },
    { name: "AsiaFM 亚洲热歌", url: "http://hot.asiafm.net:8000/asiafm", logo: "", category: "网络音乐" },
    { name: "AsiaFM 亚洲天空", url: "http://funradio.cn:8000/funradio", logo: "", category: "网络音乐" },
    { name: "AsiaFM 亚洲粤语", url: "http://yyt.asiafm.net:8000/asiafm", logo: "", category: "网络音乐" },
    { name: "80后音悦台", url: "http://stream3.hndt.com/now/SFZeH2cb/playlist.m3u8", logo: "", category: "网络音乐" },
    { name: "500首华语经典", url: "http://ls.qingting.fm/live/3412131.m3u8?bitrate=64", logo: "", category: "网络音乐" },
    { name: "Big B Radio 中文流行", url: "https://antares.dribbcast.com/proxy/cpop?mp=/s", logo: "https://bigbradio.net/sites/default/files/favicon.ico", category: "网络音乐" },
    { name: "Big B Radio 韩语流行", url: "https://antares.dribbcast.com/proxy/kpop?mp=/s", logo: "https://bigbradio.net/sites/default/files/favicon.ico", category: "网络音乐" },
    { name: "Big B Radio 日语流行", url: "https://antares.dribbcast.com/proxy/jpop?mp=/s", logo: "https://bigbradio.net/sites/default/files/favicon.ico", category: "网络音乐" },
    { name: "Big B Radio 亚洲流行", url: "https://antares.dribbcast.com/proxy/apop?mp=/s", logo: "https://bigbradio.net/sites/default/files/favicon.ico", category: "网络音乐" },
    
    // === 美国 (USA) ===
    { name: "NPR News (美国全国公共广播)", url: "https://npr-ice.streamguys1.com/live.mp3", logo: "https://www.npr.org/favicon.ico", category: "美国" },
    { name: "WNYC New York (纽约公共广播)", url: "https://fm939.wnyc.org/wnycfm-mobile.aac", logo: "https://www.wnyc.org/favicon.ico", category: "美国" },
    { name: "KEXP Seattle (西雅图独立音乐)", url: "https://kexp-mp3-128.streamguys1.com/kexp128.mp3", logo: "https://www.kexp.org/favicon.ico", category: "美国" },
    { name: "WQXR (纽约古典音乐台)", url: "https://wqxr.streaming.adswizz.com/wqxr-mobile.mp3", logo: "https://www.wqxr.org/favicon.ico", category: "美国" },
    { name: "SomaFM Groove Salad (旧金山电子)", url: "http://ice1.somafm.com/groovesalad-128-mp3", logo: "https://somafm.com/favicon.ico", category: "美国" },
    { name: "Bloomberg Radio (彭博财经)", url: "https://17563.live.streamtheworld.com/WBBRAMAAC48/HLS/aa6b0a8b-da19-463f-a757-a4e5f57df4f5/0/playlist.m3u8", logo: "https://www.bloomberg.com/favicon.ico", category: "美国" },
    { name: "Jazz24 (全天候爵士乐)", url: "https://live.wpmucdn.com/kplu/jazz24-mp3-128", logo: "https://www.jazz24.org/favicon.ico", category: "美国" },

    { name: "Rock Antenne (德国摇滚)", url: "https://mp3channels.webradio.antenne.de/rockantenne", logo: "https://www.rockantenne.de/favicon.ico", category: "网络音乐"},
    { name: "Klassik Radio (德国古典)", url: "http://edge.live.mp3.mdn.newmedia.nacamar.net/klassikradio128/livestream.mp3", logo: "https://www.klassikradio.de/favicon.ico", category: "网络音乐" },
    { name: "Radio 10 (荷兰经典流行)", url: "https://stream.radio10.nl/radio10", logo: "https://www.radio10.nl/favicon.ico",  category: "网络音乐" },
    { name: "Hot Hitz Radio (美国劲爆流行)", url: "https://hothitzradio.com/stream.mp3", logo: "https://hothitzradio.com/favicon.ico", category: "网络音乐" },
    { name: "181.FM Kickin' Country", url: "http://relay.181.fm:8130", logo: "https://www.181.fm/favicon.ico", category: "网络音乐" },
    { name: "181.FM Highway 181", url: "http://relay.181.fm:8018", logo: "https://www.181.fm/favicon.ico", category: "网络音乐" },
    { name: "181.FM 90's Country", url: "http://relay.181.fm:8050", logo: "https://www.181.fm/favicon.ico", category: "网络音乐" },
    { name: "Nashville FM WNXP(纳什维尔)", url: "https://wpln.streamguys1.com/wnxpfm.aac", logo: "https://wnxp.org/wp-content/uploads/2025/06/cropped-logo-just-letters-300x300.png", category: "网络音乐" },
    { name: "Country 108 (德国网络音乐台)", url: "http://www.country108.com/listen.m3u", logo: "https://www.country108.com/favicon.png.pagespeed.ce.tuEDsXNmeM.png", category: "网络音乐" },
    { name: "Truckers.FM (全球卡车社区)", url: "https://live.truckers.fm/", logo: "https://truckers.fm/favicon.ico", category: "网络音乐" },
    { name: "BigRigFM (卡车乡村音乐专用)", url: "https://radio.bigrig.fm/", logo: "https://bigrig.fm/favicon.ico", category: "网络音乐" },
    { name: "Simulator Radio (模拟飞行与卡车)", url: "https://stream.simulatorradio.com/stream.mp3", logo: "https://www.simulatorradio.com/favicon.ico", category: "网络音乐" }
];

console.log("Loaded at" + new Date().getTime());
